print("My name is Tyler Burke.")
print("I am 20 years old.")
print("I am majoring in Computer Science.")
print("I have only had 1 semester at BYU-Idaho.")
print("I sold my car for nearly $4000 this week!")
print("I hope I get 100% in this class.")
print("My team, Fettucine, is names after what someone ate for lunch.")
print("Fun fact, I didn't know how to spell Fettucine until now.")
print("The food at the Crossroads is overpriced.")
print("Pizza Pie Cafe is 10/10")